### ISSUE TITLE
scanner isn't accepting "no parent" as "parent_time_units"

### ISSUE THREAD

**Issue by ceblanton** [ES-DOC/esdoc-cdf2cim#5]
We (GFDL) are trying to test-publish some output for an experiment that has no parent. According to the CV, "no parent" is usually an acceptable answer for these cases. However the CDF scanner is throwing exceptions; e.g.

```
Traceback (most recent call last):
...
  File "/home/c2b/.local/lib/python2.7/site-packages/cdf2cim/parser.py", line 85, in parse
    _parse_cmip6_properties(cim2_properties, global_attributes, time_coords)
  File "/home/c2b/.local/lib/python2.7/site-packages/cdf2cim/parser.py", line 182, in _parse_cmip6_properties
    x = cf.Data([branch_time_in_parent], units=parent_time_units).dtarray[0]
  File "/home/c2b/.local/lib/python2.7/site-packages/cf/data/data.py", line 6106, in dtarray
    "Can't create date-time array from units {!r}".format(self.Units))
ValueError: Can't create date-time array from units <CF Units: no parent>
```

**Comment by iaplasg** [comment]
the same of exceptions, Is there a solution now?
